// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaxx4OXn3KExXJViaNBjihGLtQ53AVN4g',
    appId: '1:486610915574:web:31fa75da7e645d8e2b5cd7',
    messagingSenderId: '486610915574',
    projectId: 'good-transportation-app-8d9f1',
    authDomain: 'good-transportation-app-8d9f1.firebaseapp.com',
    storageBucket: 'good-transportation-app-8d9f1.appspot.com',
    measurementId: 'G-3XWKRJ37EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApVDgAp0YVPif44jT9mIHc_B87v6UvwZw',
    appId: '1:486610915574:android:f9ef87ce4027c71d2b5cd7',
    messagingSenderId: '486610915574',
    projectId: 'good-transportation-app-8d9f1',
    storageBucket: 'good-transportation-app-8d9f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH9SNuuNVuTtDLVQF2_GruHhxElOssLJo',
    appId: '1:486610915574:ios:38988fd4800ed2ee2b5cd7',
    messagingSenderId: '486610915574',
    projectId: 'good-transportation-app-8d9f1',
    storageBucket: 'good-transportation-app-8d9f1.appspot.com',
    iosBundleId: 'com.example.goodTranpotationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH9SNuuNVuTtDLVQF2_GruHhxElOssLJo',
    appId: '1:486610915574:ios:38988fd4800ed2ee2b5cd7',
    messagingSenderId: '486610915574',
    projectId: 'good-transportation-app-8d9f1',
    storageBucket: 'good-transportation-app-8d9f1.appspot.com',
    iosBundleId: 'com.example.goodTranpotationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaxx4OXn3KExXJViaNBjihGLtQ53AVN4g',
    appId: '1:486610915574:web:4c55a6c9134f1f1d2b5cd7',
    messagingSenderId: '486610915574',
    projectId: 'good-transportation-app-8d9f1',
    authDomain: 'good-transportation-app-8d9f1.firebaseapp.com',
    storageBucket: 'good-transportation-app-8d9f1.appspot.com',
    measurementId: 'G-H62BCEMY0R',
  );
}
